services:
  mosquitto-broker:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - "1883:1883" # default
      - "9001:9001" # websockets
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./logs:/mosquitto/log
  illumination:
    depends_on:
      - mosquitto-broker
    build:
      context: ./
      dockerfile: ./illumination/Dockerfile
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - TZ=Europe/Warsaw
    volumes:
      - ./logs:/var/logs
      - .env:/usr/src/app/config/.env
  diagnostics:
    depends_on:
      - mosquitto-broker
    build:
      context: ./
      dockerfile: ./diagnostics/Dockerfile
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - TZ=Europe/Warsaw
    volumes:
      - ./logs:/var/logs
      - .env:/usr/src/app/config/.env
  camera:
    depends_on:
      - mosquitto-broker
    build:
      context: ./
      dockerfile: ./camera/Dockerfile
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/media4:/dev/media4
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - TZ=Europe/Warsaw
    volumes:
      - ./logs:/var/logs
      - .env:/usr/src/app/config/.env

networks:
  default:
    name: "plants-default"
