# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    types: [opened, reopened]
  push:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          echo "Running diag"
          ls -la
          pwd
          echo "stop stop stop"
          cat Makefile
          make dev

  linter:
    name: Format checkers
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - run: |
        source ./venv/bin/activate
        flake8 --exclude venv --count --max-line-length=120 --statistics
    - run: |
        source ./venv/bin/activate
        black --exclude venv --check .
  tests:
    name: Run pytest UTs
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
    - run: |
        make tests
